[package]
name = "api-macros"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["derive"] }

[dev-dependencies]
api-core = { path = "../api-core" }
trybuild = "1.0"

[lints]
workspace = true
