[package]
name = "api-macros"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["derive", "full"] }

[dev-dependencies]
api-axum = { path = "../api-axum" }
api-core = { path = "../api-core" }
api-gen-effect-v4 = { path = "../api-gen-effect-v4" }
bytes = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trybuild = "1.0"

[lints]
workspace = true
