[package]
name = "typeweld-cli"
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "typeweld"
path = "src/main.rs"

[features]
default = ["embedded-semantic-scanner"]
embedded-semantic-scanner = ["dep:deno_core"]

[dependencies]
typeweld-build = { version = "0.0.1", path = "../typeweld-build" }
typeweld-core = { version = "0.0.1", path = "../typeweld-core" }
typeweld-gen-effect-v4 = { version = "0.0.1", path = "../typeweld-gen-effect-v4" }
typeweld-ir = { version = "0.0.1", path = "../typeweld-ir" }
cargo_metadata = "0.23.1"
clap = { version = "4.6.1", features = ["derive"] }
deno_core = { version = "0.403.0", optional = true }
dialoguer = "0.12.0"
notify-debouncer-full = "0.8.0-rc.2"
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
syn = { version = "2.0.117", features = ["full"] }

[dev-dependencies]
typeweld-test-fixtures = { path = "../typeweld-test-fixtures" }

[lints]
workspace = true
