[package]
name = "api-axum"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
api-core = { path = "../api-core" }
axum = { version = "0.8", default-features = false, features = ["json", "query", "tokio"] }
futures-util = "0.3"
http = "1.0"
serde = "1.0"
tower-layer = "0.3"
tower-service = "0.3"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["macros", "rt"] }
tower = { version = "0.5", features = ["util"] }

[lints]
workspace = true
