[package]
name = "monorepo-basic"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
api-axum = { path = "../../crates/api-axum" }
api-collector = { path = "../../crates/api-collector" }
api-core = { path = "../../crates/api-core" }
api-macros = { path = "../../crates/api-macros" }
serde = { version = "1.0", features = ["derive"] }

[lints]
workspace = true
