[package]
name = "monorepo-basic"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
typeweld-axum = { path = "../../crates/typeweld-axum" }
typeweld-cli = { path = "../../crates/typeweld-cli" }
typeweld-core = { path = "../../crates/typeweld-core" }
typeweld-macros = { path = "../../crates/typeweld-macros" }
serde = { version = "1.0.228", features = ["derive"] }

[lints]
workspace = true
