[package]
name = "typeweld-axum"
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
typeweld-core = { version = "0.0.5", path = "../typeweld-core" }
axum = { version = "0.8.9", default-features = false, features = ["json", "query", "tokio"] }
futures-util = "0.3.32"
http = "1.4.1"
serde = "1.0.228"
tower-layer = "0.3.3"
tower-service = "0.3.3"

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["macros", "rt"] }
tower = { version = "0.5.3", features = ["util"] }

[lints]
workspace = true
